### ISSUE TITLE
Can you use templates like `rticles` with Quarto?

### ISSUE THREAD

**Issue by njtierney** [njtierney/qmd4sci#6]
In rmd4sci I had this note, which was around if you wanted to use special citation features of something like the plot_article...I'm not sure how this applied to quarto

> If you are using a template of some kind, such as those in `rticles`, and want the full featured citation features, then your YAML will need to include something like this:

```yaml
output:
  bookdown::pdf_book:
    base_format: rticles::plos_article
```
